### PR TITLE
fix for travis test downloading corrected version,..

### PR DESCRIPTION
**Pull request by mckaygerhard**
fix the download url for travis tests suites

### CODE REVIEW

**Comment by mckaygerhard** [comment]
why my checks failed? the download url are correct!

**Comment by mckaygerhard** [comment]
with this php 5.4+ works perfectly, but still failds with 5.5 and 5.3 see log, seems path include changed with those versions:

``` bash
0.26s$ wget "https://github.com/osTicket/osTicket/archive/v${OSTICKET_VERSION}.tar.gz" -O ot.tgz
--2018-01-11 14:16:06--  https://github.com/osTicket/osTicket/archive/v1.9.16.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/osTicket/osTicket/tar.gz/v1.9.16 [following]
--2018-01-11 14:16:06--  https://codeload.github.com/osTicket/osTicket/tar.gz/v1.9.16
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6694791 (6.4M) [application/x-gzip]
Saving to: ‘ot.tgz’
100%[======================================>] 6,694,791   --.-K/s   in 0.1s    
2018-01-11 14:16:07 (53.4 MB/s) - ‘ot.tgz’ saved [6694791/6694791]
install.2
0.21s$ tar xvf ot.tgz && mv osTicket-${OSTICKET_VERSION} ../osticket
0.03s$ phpenv config-rm xdebug.ini
File xdebug.ini removed from /home/travis/.phpenv/versions/5.5/etc/conf.d.
before_script.2
0.34s$ ! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"
before_script.3
0.03s$ echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
0.36s$ phpunit
PHP Warning:  include(/home/travis/build/clonemeagain/attachment_preview/tests/plugin.php): failed to open stream: No such file or directory in /home/travis/build/clonemeagain/osticket/include/class.plugin.php on line 280
Warning: include(/home/travis/build/clonemeagain/attachment_preview/tests/plugin.php): failed to open stream: No such file or directory in /home/travis/build/clonemeagain/osticket/include/class.plugin.php on line 280
PHP Warning:  include(): Failed opening '/home/travis/build/clonemeagain/attachment_preview/tests/plugin.php' for inclusion (include_path='.:/home/travis/.phpenv/versions/5.5.38/share/pear') in /home/travis/build/clonemeagain/osticket/include/class.plugin.php on line 280
Warning: include(): Failed opening '/home/travis/build/clonemeagain/attachment_preview/tests/plugin.php' for inclusion (include_path='.:/home/travis/.phpenv/versions/5.5.38/share/pear') in /home/travis/build/clonemeagain/osticket/include/class.plugin.php on line 280
PHP Warning:  array_merge(): Argument #2 is not an array in /home/travis/build/clonemeagain/osticket/include/class.plugin.php on line 280
Warning: array_merge(): Argument #2 is not an array in /home/travis/build/clonemeagain/osticket/include/class.plugin.php on line 280
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /home/travis/build/clonemeagain/attachment_preview/tests/AttachmentPreviewPluginTest.php on line 14
Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /home/travis/build/clonemeagain/attachment_preview/tests/AttachmentPreviewPluginTest.php on line 14
The command "phpunit" exited with 255.
```

**Comment by mckaygerhard** [comment]
phpunit for 5.3 and 5.5 are different?

**Comment by clonemeagain** [comment]
Ahh, you're looking at Travis results for the PHP 5.3 PR, I broke it yesterday by adding PHP 5.3 to the Travis config (it was never there before), now the install script needs to be rewritten to use the env OSTICKET_VERSION so we don't try and use osTicket 1.10 on PHP 5.3, which is not compatible.

**Comment by mckaygerhard** [comment]
waith, i search at travis..  rewritten to use the env OSTICKET_VERSION? i dont see somuch usage there

the scriopt alredy acepts that osTicket 1.10 on PHP 5.3 are not evaluate ar valid..

i'm taking about 1.9 (1.9.16 seee the pull) agains 5.3 that fails..

**Comment by clonemeagain** [comment]
Might work when the PHP 5.3 PR version is merged mate, as the tests themselves needed to be modified to use PHP 5.3 syntax lol. I'll try and fold this into the other PR, unless you are able to, then please do.

**Comment by clonemeagain** [comment]
Ok, apparently I can just merge this into it, but not with my phone.

"Pull requests that have a failing status can’t be merged on a phone."
Give me a few hours to get into the office mate.

**Comment by mckaygerhard** [comment]
what? umm interesting, might tests if gitlab merge interface can be done using phone! tha's mark a great difference for a github vs gitlab review?

**Comment by clonemeagain** [comment]
Well, it can, just not when you've configured Travis tests and one is failing apparently. Didn't know that lol

**Pull request merged**
